name: download-youtube-direct

on:
  workflow_dispatch:        # 允许手动触发
  # 也可改成 push / schedule 等

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download video
        run: |
          mkdir -p dist
          curl ${{ secrets.PARAMS }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-video
          path: dist/
