name: download-file

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Install yt-dlp
        run: pip install yt-dlp
          
      - name: Download video
        run: yt-dlp -f bestvideo+bestaudio ${{ secrets.VIDEO }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: files
          path: '*'
